name: olronn

dependencies:
  - python=3.9
  - pip: 
    - -e .
    - river
    - torch
    - numpy
    - pandas 
    - jupyter
    - matplotlib
    - scikit-learn
    - dog-optimizer
    - dadaptation
    - tqdm